version: '3.7'

services:
  api-solid-pg:
    image: 'bitnami/postgresql'
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - default

  api_backend:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - api-solid-pg
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres:
    name: postgres
